name: CI-compile

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ps2homebrew/ps2homebrew:main
    steps:
    - name: git checkout
      uses: actions/checkout@v3

    - run: make

    - name: Upload release artifact ELF
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        path: |
          *.elf
          *.ELF
